### ISSUE TITLE
List index error with empty lines

### ISSUE THREAD

**Issue by MerlinR** [Akselmo/ESOLinuxAddonManager#17]
Small issue i encountered, I wished to keep lib's and addons separate so separated with an empty line, this causes a list index error:
`Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/esoAddon/ESOLinuxAddonManager/addondownloader.py", line 38, in start
    file = self.download(link, self.file_number)
  File "/opt/esoAddon/ESOLinuxAddonManager/addondownloader.py", line 63, in download
    info = re.findall("https://www.esoui.com/downloads/info(\d*)", link)[0]
IndexError: list index out of range
`
This would be resolved by https://github.com/Akselmo/ESOLinuxAddonManager/issues/10

**Comment by Akselmo** [comment]
Thanks, will look into it when I got time. The complete rework of the app will fix this, but I may push a hotfix for the current one when I can
