### ISSUE TITLE
SSL certificate error

### ISSUE THREAD

**Issue by booty-bandit** [Akselmo/ESOLinuxAddonManager#21]
When running the appimage version, after pressing the download button the following error is outputted, and nothing is downloaded.  The python version works fine however.

Exception in thread Thread-1 (start):
Traceback (most recent call last):
  File "/tmp/.mount_ESOLinhiD7PY/urllib/request.py", line 1348, in do_open
  File "/tmp/.mount_ESOLinhiD7PY/http/client.py", line 1282, in request
  File "/tmp/.mount_ESOLinhiD7PY/http/client.py", line 1328, in _send_request
  File "/tmp/.mount_ESOLinhiD7PY/http/client.py", line 1277, in endheaders
  File "/tmp/.mount_ESOLinhiD7PY/http/client.py", line 1037, in _send_output
  File "/tmp/.mount_ESOLinhiD7PY/http/client.py", line 975, in send
  File "/tmp/.mount_ESOLinhiD7PY/http/client.py", line 1454, in connect
  File "/tmp/.mount_ESOLinhiD7PY/ssl.py", line 512, in wrap_socket
  File "/tmp/.mount_ESOLinhiD7PY/ssl.py", line 1070, in _create
  File "/tmp/.mount_ESOLinhiD7PY/ssl.py", line 1341, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/.mount_ESOLinhiD7PY/threading.py", line 1009, in _bootstrap_inner
  File "/tmp/.mount_ESOLinhiD7PY/threading.py", line 946, in run
  File "/tmp/.mount_ESOLinhiD7PY/addondownloader.py", line 40, in start
  File "/tmp/.mount_ESOLinhiD7PY/addondownloader.py", line 69, in download
  File "/tmp/.mount_ESOLinhiD7PY/urllib/request.py", line 216, in urlopen
  File "/tmp/.mount_ESOLinhiD7PY/urllib/request.py", line 519, in open
  File "/tmp/.mount_ESOLinhiD7PY/urllib/request.py", line 536, in _open
  File "/tmp/.mount_ESOLinhiD7PY/urllib/request.py", line 496, in _call_chain
  File "/tmp/.mount_ESOLinhiD7PY/urllib/request.py", line 1391, in https_open
  File "/tmp/.mount_ESOLinhiD7PY/urllib/request.py", line 1351, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>

**Comment by Akselmo** [comment]
Notes:

- Problem seems to happen only when running the appimage, not when running directly from python
    - Is appimage being blocked somehow from downloading?

**Comment by Akselmo** [comment]
Some updates

The issue seems to happen when the appimage cant find the TSL certificate on the machine if the path differs from the one in Fedora 36

certifi.where() doesnt work

Need to ask Nuitka devs whats going on

**Comment by Akselmo** [comment]
There's a test for fixing this by disabling the SSL cert lookup in https://github.com/Akselmo/ESOLinuxAddonManager/releases/tag/1.2.3

**Comment by Akselmo** [comment]
The certification location is not dynamic: when compiled with nuitka it gets the cert location and its always the one used by the build machine.

**Comment by Akselmo** [comment]
Should be fixed now: https://github.com/Akselmo/ESOLinuxAddonManager/releases/tag/1.2.5

If it doesn't work for you, try this instead: https://github.com/Akselmo/ESOLinuxAddonManager/releases/tag/1.2.3-no-certs
